# Generated by Django 4.2.6 on 2023-11-19 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkart_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
