# Generated by Django 4.2.6 on 2023-11-21 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkart_app', '0003_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
