# Generated by Django 4.2.6 on 2023-12-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkart_app', '0005_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='image',
        ),
    ]
