# Generated by Django 4.2.6 on 2023-12-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkart_app', '0006_rename_image_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='Image',
        ),
    ]
